# Generated by Django 6.0.1 on 2026-02-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('address', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default='0.0', max_digits=2)),
                ('description', models.TextField(blank=True, null=True)),
                ('res_phone', models.CharField(max_length=15)),
                ('res_image', models.ImageField(upload_to='restaurants/')),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
