# Generated by Django 6.0.1 on 2026-01-22 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0002_alter_category_cat_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_image', models.ImageField(upload_to='item_images')),
                ('price', models.PositiveIntegerField()),
                ('rating', models.FloatField(blank=True, default=0.0, null=True)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField()),
                ('is_veg', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodApp.category')),
            ],
        ),
    ]
