# Generated by Django 6.0.1 on 2026-02-01 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0007_order_orderitem'),
        ('restaurantApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='restaurent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='restaurantApp.restaurant'),
        ),
    ]
